# yaml-language-server: $schema=https://raw.githubusercontent.com/Ensono/eirctl/refs/heads/main/schemas/schema_v1.json

import:
  - https://raw.githubusercontent.com/thepaulmacca-ensono/eirctl-configurations/refs/heads/main/shared/contexts.yaml
  - https://raw.githubusercontent.com/thepaulmacca-ensono/eirctl-configurations/refs/heads/main/security/linting.yaml
  - https://raw.githubusercontent.com/thepaulmacca-ensono/eirctl-configurations/refs/heads/main/security/scanning.yaml
  - https://raw.githubusercontent.com/thepaulmacca-ensono/eirctl-configurations/refs/heads/main/infra/terraform.yaml

watchers:
  lint:
    watch: ["*.yml"]
    events: [create, write]
    task: lint:yaml
  terraform:
    watch: ["*.tf", "*.tfvars"]
    events: [create, write]
    task: lint:terraform:format

pipelines:
  code:linting:
    - task: lint:yaml
    - task: lint:terraform:format
      depends_on: lint:yaml
    - task: lint:terraform:validate
      depends_on: lint:terraform:format
    - task: lint:terraform:tflint
      depends_on: lint:terraform:validate

  code:scanning:
    - task: scan:terraform:checkov

  code:documentation:
    - task: doc:terraform:generate

  infrastructure:plan:
    - task: terraform:init
    - task: terraform:plan
      depends_on: terraform:init

  infrastructure:apply:
    - task: terraform:init
    - task: terraform:apply
      depends_on: terraform:init

  infrastructure:destroy:plan:
    - task: terraform:init
    - task: terraform:destroy:plan
      depends_on: terraform:init

  infrastructure:destroy:apply:
    - task: terraform:init
    - task: terraform:destroy:apply
      depends_on: terraform:init
