# yaml-language-server: $schema=https://raw.githubusercontent.com/Ensono/eirctl/refs/heads/main/schemas/schema_v1.json

import:
  - https://raw.githubusercontent.com/Ensono/stacks-eirctl-configurations/refs/heads/feat/initial-configs/shared/contexts.yaml
  - https://raw.githubusercontent.com/Ensono/stacks-eirctl-configurations/refs/heads/feat/initial-configs/security/linting.yaml
  - https://raw.githubusercontent.com/Ensono/stacks-eirctl-configurations/refs/heads/feat/initial-configs/infra/terraform.yaml

watchers:
  lint:
    watch: ["*.yml"]
    events: [create, write]
    task: lint:yaml
  terraform:
    watch: ["*.tf", "*.tfvars"]
    events: [create, write]
    task: lint:terraform:format

pipelines:
  lint:
    - task: lint:yaml
    - task: lint:terraform:format
      depends_on: lint:yaml
